### ISSUE TITLE
An error:- when open admin<system<configuration<payment method

### ISSUE THREAD

**Issue by Vapeelectronics** [bitpay/bitpay-checkout-magento#20]
Warning: include(/homepages/7/d715943769/htdocs/includes/src/BitpayCheckout_BPCheckout_Helper_Data.php): failed to open stream: No such file or directory  in /homepages/7/d715943769/htdocs/includes/src/Varien_Autoload.php on line 94

#0 /homepages/7/d715943769/htdocs/includes/src/Varien_Autoload.php(94): mageCoreErrorHandler(2, 'include(/homepa...', '/homepages/7/d7...', 94, Array)
#1 /homepages/7/d715943769/htdocs/includes/src/Varien_Autoload.php(94): include()
#2 [internal function]: Varien_Autoload->autoload('BitpayCheckout_...')
#3 /homepages/7/d715943769/htdocs/app/Mage.php(547): spl_autoload_call('BitpayCheckout_...')
#4 /homepages/7/d715943769/htdocs/includes/src/Mage_Adminhtml_Block_System_Config_Form.php(194): Mage::helper('bpcheckout')
#5 /homepages/7/d715943769/htdocs/includes/src/Mage_Adminhtml_Block_System_Config_Form.php(164): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#6 /homepages/7/d715943769/htdocs/includes/src/Mage_Adminhtml_Block_System_Config_Edit.php(92): Mage_Adminhtml_Block_System_Config_Form->initForm()
#7 /homepages/7/d715943769/htdocs/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(107): Mage_Adminhtml_Block_System_Config_Edit->initForm()
#8 /homepages/7/d715943769/htdocs/includes/src/__default.php(14339): Mage_Adminhtml_System_ConfigController->editAction()
#9 /homepages/7/d715943769/htdocs/includes/src/__default.php(18831): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /homepages/7/d715943769/htdocs/includes/src/__default.php(18361): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /homepages/7/d715943769/htdocs/includes/src/__default.php(21317): Mage_Core_Controller_Varien_Front->dispatch()
#12 /homepages/7/d715943769/htdocs/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#13 /homepages/7/d715943769/htdocs/index.php(85): Mage::run('', 'store')
#14 {main}

**Comment by Vapeelectronics** [comment]
help-wanted
